# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



























trigger:
- master   # 触发分支，你的主分支名字改一下

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'   # PyTorch 推荐的 Python 版本
    addToPath: true

- script: |

    echo "hello world"
    python -m pip install --upgrade pip setuptools wheel build torch==2.5.1+cu121 torchvision --index-url https://download.pytorch.org/whl/cu121
    python -m build
  displayName: 'Build wheel'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'dist'
    artifactName: 'python-wheels'